import './style.css';
const CHANNEL = 'https://www.youtube.com/@MirabiliumOfficial';
const $ = (selector) => document.querySelector(selector);
const text = {
  en: { navExplore:'Explore',navAbout:'The story',navCommunity:'Community',navWatch:'Watch on YouTube',eyebrow:'THE WORLD IS MORE INTERESTING THAN YOU THINK',headline:'Stay curious.<br><em>Look closer.</em>',intro:'A home for curious minds. Discover extraordinary stories about history, science, mysteries and the world around us — told in Malayalam.',explore:'Explore the channel',scroll:'SCROLL TO DISCOVER',statSubs:'SUBSCRIBERS',statVideos:'VIDEOS',statViews:'TOTAL VIEWS',statNote:'Public YouTube data · refreshes about every 10 minutes',chapter:'01 / THE DISCOVERY',latest:'Stories worth<br><em>uncovering.</em>',latestDesc:'Every question is the beginning of a good story. Catch the latest from Mirabilium.',allVideos:'View all videos',aboutLabel:'02 / THE PERSON BEHIND IT',aboutTitle:'Meet the mind<br>behind <em>Mirabilium.</em>',aboutBody:'Created by Jinan, Mirabilium turns fascinating facts, mysteries, history, science and discoveries into Malayalam videos made for the endlessly curious.',aboutQuote:'Observe the ordinary. Uncover the extraordinary.',aboutTag:'NEW STORIES EVERY WEEK',reviewLabel:'03 / YOUR VOICE',reviewTitle:'What did you<br><em>discover?</em>',reviewDesc:'Enjoying the journey? Leave a note for Jinan and the Mirabilium community.',reviewName:'Your name',reviewMessage:'What do you think of the channel?',reviewRate:'Your rating',reviewSend:'Post review',reviewEmpty:'Be the first to leave a review.',reviewUnavailable:'Reviews are not connected yet. Set up Supabase to enable public reviews.',reviewError:'Reviews are temporarily unavailable.',reviewSuccess:'Your review is now public. Thank you!',reviewFailed:'Could not post your review. Please try again.',videosUnavailable:'Latest videos will appear here once the YouTube API is configured.',channelCta:'Explore the videos on YouTube',footer:'A little curiosity changes everything.',credit:'Website by Alwin Susy Jayan',fresh:'Updated' },
  ml: { navExplore:'വീഡിയോകൾ',navAbout:'ഞങ്ങളെക്കുറിച്ച്',navCommunity:'അഭിപ്രായങ്ങൾ',navWatch:'യൂട്യൂബിൽ കാണൂ',eyebrow:'ലോകം നിങ്ങൾ കരുതുന്നതിലും കൗതുകകരമാണ്',headline:'കൗതുകത്തോടെ നോക്കൂ.<br><em>കൂടുതൽ അറിയൂ.</em>',intro:'കൗതുകമുള്ള മനസ്സുകൾക്കായി ഒരിടം. ചരിത്രം, ശാസ്ത്രം, നിഗൂഢതകൾ, ലോകത്തിലെ അത്ഭുതങ്ങൾ — എല്ലാം മലയാളത്തിൽ.',explore:'ചാനൽ കാണൂ',scroll:'താഴേക്ക് നോക്കൂ',statSubs:'സബ്‌സ്‌ക്രൈബർമാർ',statVideos:'വീഡിയോകൾ',statViews:'ആകെ കാഴ്ചകൾ',statNote:'യൂട്യൂബിലെ പൊതുവിവരങ്ങൾ · ഏകദേശം 10 മിനിറ്റിൽ പുതുക്കുന്നു',chapter:'01 / കണ്ടെത്തലുകൾ',latest:'അറിയാൻ കൊതിപ്പിക്കുന്ന<br><em>കഥകൾ.</em>',latestDesc:'ഓരോ ചോദ്യവും ഒരു നല്ല കഥയുടെ തുടക്കമാണ്. Mirabilium-ന്റെ പുതിയ വീഡിയോകൾ കാണൂ.',allVideos:'എല്ലാ വീഡിയോകളും',aboutLabel:'02 / പിന്നിലെ വ്യക്തി',aboutTitle:'Mirabilium-ന്റെ പിന്നിലെ<br><em>ജിനാനെ പരിചയപ്പെടൂ.</em>',aboutBody:'ജിനാൻ ഒരുക്കുന്ന Mirabilium, കൗതുകകരമായ വസ്തുതകളും നിഗൂഢതകളും ചരിത്രവും ശാസ്ത്രവും കണ്ടെത്തലുകളും മലയാളത്തിൽ അവതരിപ്പിക്കുന്നു.',aboutQuote:'ചുറ്റും നോക്കൂ. അത്ഭുതങ്ങൾ കണ്ടെത്തൂ.',aboutTag:'എല്ലാ ആഴ്ചയും പുതിയ കഥകൾ',reviewLabel:'03 / നിങ്ങളുടെ അഭിപ്രായം',reviewTitle:'നിങ്ങൾ എന്താണ്<br><em>കണ്ടെത്തിയത്?</em>',reviewDesc:'ചാനൽ ഇഷ്ടമായോ? ജിനാനും Mirabilium സമൂഹത്തിനുമായി ഒരു അഭിപ്രായം എഴുതൂ.',reviewName:'നിങ്ങളുടെ പേര്',reviewMessage:'ചാനലിനെക്കുറിച്ച് എന്താണ് അഭിപ്രായം?',reviewRate:'നിങ്ങളുടെ റേറ്റിംഗ്',reviewSend:'അഭിപ്രായം പോസ്റ്റ് ചെയ്യൂ',reviewEmpty:'ആദ്യ അഭിപ്രായം നിങ്ങളുടേതാകട്ടെ.',reviewUnavailable:'പൊതു അഭിപ്രായങ്ങൾ പ്രവർത്തിക്കാൻ Supabase സജ്ജീകരിക്കണം.',reviewError:'അഭിപ്രായങ്ങൾ ഇപ്പോൾ ലഭ്യമല്ല.',reviewSuccess:'നിങ്ങളുടെ അഭിപ്രായം പ്രസിദ്ധീകരിച്ചു. നന്ദി!',reviewFailed:'അഭിപ്രായം പോസ്റ്റ് ചെയ്യാനായില്ല. വീണ്ടും ശ്രമിക്കൂ.',videosUnavailable:'YouTube API സജ്ജീകരിച്ചാൽ പുതിയ വീഡിയോകൾ ഇവിടെ കാണാം.',channelCta:'യൂട്യൂബിൽ വീഡിയോകൾ കാണൂ',footer:'ഒരു ചെറിയ കൗതുകം പോലും എല്ലാം മാറ്റും.',credit:'വെബ്സൈറ്റ്: Alwin Susy Jayan',fresh:'പുതുക്കിയത്' }
};
let lang = localStorage.getItem('mirabilium-language') === 'ml' ? 'ml' : 'en';
let channelData = null, reviews = [], reviewStatus = '', statusType = '';
const supaUrl = (import.meta.env.VITE_SUPABASE_URL || '').replace(/\/$/, '');
const supaKey = import.meta.env.VITE_SUPABASE_ANON_KEY || '';
const configured = Boolean(supaUrl && supaKey);
function escapeHTML(value) { return String(value).replace(/[&<>"']/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch])); }
function n(value) { return Number.isFinite(value) ? new Intl.NumberFormat(lang === 'ml' ? 'ml-IN' : 'en-CA').format(value) : '—'; }
function date(value) { return new Intl.DateTimeFormat(lang === 'ml' ? 'ml-IN' : 'en-CA', { year:'numeric',month:'short',day:'numeric' }).format(new Date(value)); }
function sectionTemplate() {
 const t=text[lang]; document.documentElement.lang=lang;
 $('#app').innerHTML=`<header class="nav"><a class="wordmark" href="#top" aria-label="Mirabilium home">M<span>✦</span></a><nav aria-label="Main navigation"><a href="#explore">${t.navExplore}</a><a href="#about">${t.navAbout}</a><a href="#community">${t.navCommunity}</a></nav><div class="nav-actions"><button class="language" id="language" aria-label="Switch language to ${lang==='en'?'Malayalam':'English'}">${lang==='en'?'മലയാളം':'English'} <span>↗</span></button><a class="nav-yt" href="${CHANNEL}" target="_blank" rel="noopener noreferrer">${t.navWatch} <span>↗</span></a></div></header>
 <main id="top"><section class="hero"><div class="hero-glow"></div><div class="hero-inner"><div class="hero-content"><p class="kicker"><span class="dot"></span>${t.eyebrow}</p><h1>${t.headline}</h1><p class="hero-copy">${t.intro}</p><div class="hero-buttons"><a class="button-primary" href="#explore">${t.explore} <span>↗</span></a><a class="button-ghost" href="${CHANNEL}" target="_blank" rel="noopener noreferrer"><span class="play-icon">▶</span> ${t.navWatch}</a></div></div><div class="hero-art" aria-label="Mirabilium channel banner"><div class="halo"></div><div class="banner-frame"><img src="/banner.jpg" alt="Mirabilium — Observe and Uncover banner"/></div><div class="orbit orbit-one"></div><div class="orbit orbit-two"></div><span class="star star-one">✦</span><span class="star star-two">✧</span></div></div><div class="hero-bottom"><span>${t.scroll} ↓</span><span>MIRABILIUM · OBSERVE & UNCOVER</span></div></section>
 <section class="stats" aria-label="Channel statistics"><div><strong id="subs">—</strong><span>${t.statSubs}</span></div><div><strong id="videos-count">—</strong><span>${t.statVideos}</span></div><div><strong id="views">—</strong><span>${t.statViews}</span></div><p id="stat-note">${t.statNote}</p></section>
 <section class="section explore" id="explore"><div class="section-head"><div><p class="eyebrow">${t.chapter}</p><h2>${t.latest}</h2></div><div class="section-side"><p>${t.latestDesc}</p><a class="text-link" href="${CHANNEL}/videos" target="_blank" rel="noopener noreferrer">${t.allVideos} ↗</a></div></div><div id="video-grid" class="video-grid"></div></section>
 <section class="about" id="about"><div class="about-card"><div class="about-visual"><div class="about-ring">M</div><span class="about-small">OBSERVE<br>& UNCOVER</span></div><div class="about-copy"><p class="eyebrow">${t.aboutLabel}</p><h2>${t.aboutTitle}</h2><p>${t.aboutBody}</p><div class="about-rule"></div><span class="pill">✦ ${t.aboutTag}</span></div></div><p class="quote">“${t.aboutQuote}”</p></section>
 <section class="section community" id="community"><div class="section-head"><div><p class="eyebrow">${t.reviewLabel}</p><h2>${t.reviewTitle}</h2></div><p class="section-side">${t.reviewDesc}</p></div><div class="community-layout"><form id="review-form" class="review-form"><label for="name">${t.reviewName}</label><input id="name" name="name" type="text" required minlength="2" maxlength="40" autocomplete="name" placeholder="${t.reviewName}"/><label for="rating">${t.reviewRate}</label><select id="rating" name="rating" required><option value="5">★★★★★ · 5</option><option value="4">★★★★☆ · 4</option><option value="3">★★★☆☆ · 3</option><option value="2">★★☆☆☆ · 2</option><option value="1">★☆☆☆☆ · 1</option></select><label for="message">${t.reviewMessage}</label><textarea id="message" name="message" required minlength="10" maxlength="500" rows="5" placeholder="${t.reviewMessage}"></textarea><div class="trap" aria-hidden="true"><label for="website">Website</label><input id="website" name="website" tabindex="-1" autocomplete="off"/></div><button type="submit" class="button-primary" ${configured?'':'disabled'}>${t.reviewSend} <span>↗</span></button><p class="form-status ${statusType}" role="status">${escapeHTML(reviewStatus || (configured?'':t.reviewUnavailable))}</p></form><div class="review-list" id="review-list"></div></div></section>
 <section class="final-cta"><p class="eyebrow">MIRABILIUM · OBSERVE & UNCOVER</p><h2>${t.footer}</h2><a class="button-primary" href="${CHANNEL}" target="_blank" rel="noopener noreferrer">${t.channelCta} <span>↗</span></a></section></main><footer><a class="footer-logo" href="#top">Mirabilium<span>.</span></a><span>© ${new Date().getFullYear()} Mirabilium</span><span>${t.credit}</span><a href="${CHANNEL}" target="_blank" rel="noopener noreferrer">YouTube ↗</a></footer>`;
 $('#language').onclick=()=>{lang=lang==='en'?'ml':'en';localStorage.setItem('mirabilium-language',lang);sectionTemplate();};
 $('#review-form').onsubmit=submitReview;
 renderChannel(); renderReviews();
}
function renderChannel() {const t=text[lang];if(channelData){$('#subs').textContent=n(channelData.subscribers);$('#videos-count').textContent=n(channelData.videoCount);$('#views').textContent=n(channelData.views);if(channelData.fetchedAt) $('#stat-note').textContent=`${t.fresh} ${date(channelData.fetchedAt)} · ${t.statNote}`;}const videos=channelData?.videos||[];$('#video-grid').innerHTML=videos.length?videos.map((video,i)=>`<a class="video-card" href="https://www.youtube.com/watch?v=${encodeURIComponent(video.id)}" target="_blank" rel="noopener noreferrer"><div class="video-thumb">${video.thumbnail?`<img loading="lazy" src="${escapeHTML(video.thumbnail)}" alt=""/>`:''}<span class="video-play">▶</span></div><div class="video-meta"><span>0${i+1} / MIRABILIUM</span><span>↗</span></div><h3>${escapeHTML(video.title)}</h3></a>`).join(''):`<a class="video-fallback" href="${CHANNEL}/videos" target="_blank" rel="noopener noreferrer"><span class="video-fallback-orb">✦</span><span>${t.videosUnavailable}</span><strong>${t.channelCta} ↗</strong></a>`;}
function renderReviews(){const t=text[lang];$('#review-list').innerHTML=reviews.length?reviews.map(review=>`<article class="review"><div class="review-top"><div class="avatar">${escapeHTML(review.name.trim().charAt(0).toUpperCase())}</div><div><strong>${escapeHTML(review.name)}</strong><time datetime="${escapeHTML(review.created_at)}">${date(review.created_at)}</time></div><span class="stars" aria-label="${Number(review.rating)} out of 5 stars">${'★'.repeat(review.rating)}${'☆'.repeat(5-review.rating)}</span></div><p>${escapeHTML(review.message)}</p></article>`).join(''):`<div class="review-empty"><span>✦</span><p>${configured?t.reviewEmpty:t.reviewUnavailable}</p></div>`;}
async function loadChannel(){try{const response=await fetch('/api/channel');if(!response.ok)throw new Error('Unavailable');channelData=await response.json();renderChannel();}catch{ /* The site remains navigable when the API is not configured or YouTube is unavailable. */ }}
async function supa(path,options={}){const response=await fetch(`${supaUrl}/rest/v1/${path}`,{...options,headers:{apikey:supaKey,'Content-Type':'application/json',...(options.headers||{})}});if(!response.ok)throw new Error(`Supabase ${response.status}`);if(response.status===204||options.method==='POST')return null;return response.json();}
async function loadReviews(){if(!configured)return;try{reviews=await supa('reviews?select=id,name,message,rating,created_at&order=created_at.desc&limit=12');renderReviews();}catch{reviewStatus=text[lang].reviewError;statusType='error';$('.form-status').textContent=reviewStatus;}}
async function submitReview(event){event.preventDefault();if(!configured)return;const form=event.currentTarget;if(form.elements.namedItem('website').value)return;const name=form.elements.namedItem('name').value.trim(),message=form.elements.namedItem('message').value.trim(),rating=Number(form.elements.namedItem('rating').value);if(name.length<2||name.length>40||message.length<10||message.length>500||!Number.isInteger(rating)||rating<1||rating>5)return;const button=form.querySelector('button[type=submit]');button.disabled=true;try{await supa('reviews',{method:'POST',headers:{Prefer:'return=minimal'},body:JSON.stringify({name,message,rating})});form.reset();reviewStatus=text[lang].reviewSuccess;statusType='success';await loadReviews();}catch{reviewStatus=text[lang].reviewFailed;statusType='error';}finally{button.disabled=false;$('.form-status').textContent=reviewStatus;$('.form-status').className=`form-status ${statusType}`;}}
sectionTemplate();loadChannel();loadReviews();setInterval(loadChannel,10*60*1000);
